-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 24 avr. 2024 à 07:13
-- Version du serveur : 8.2.0
-- Version de PHP : 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `slam-site_streaming_devoir`
--

-- --------------------------------------------------------

--
-- Structure de la table `appartenir`
--

DROP TABLE IF EXISTS `appartenir`;
CREATE TABLE IF NOT EXISTS `appartenir` (
  `id_f` int NOT NULL,
  `id_c` int NOT NULL,
  PRIMARY KEY (`id_f`,`id_c`),
  KEY `id_c` (`id_c`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Structure de la table `category`
--

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `id_c` int NOT NULL AUTO_INCREMENT,
  `libelle_cat` varchar(50) NOT NULL,
  PRIMARY KEY (`id_c`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `category`
--

INSERT INTO `category` (`id_c`, `libelle_cat`) VALUES
(1, 'Science-Fiction'),
(2, 'Action'),
(3, 'Aventure'),
(4, 'Horreur'),
(5, 'Western');

-- --------------------------------------------------------

--
-- Structure de la table `film`
--

DROP TABLE IF EXISTS `film`;
CREATE TABLE IF NOT EXISTS `film` (
  `id_f` int NOT NULL AUTO_INCREMENT,
  `nom_f` varchar(55) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `duree_f` int NOT NULL,
  `description_f` text NOT NULL,
  `lien_f` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `image_f` varchar(999) NOT NULL,
  `catégorie` varchar(50) NOT NULL,
  `id_c` int NOT NULL,
  PRIMARY KEY (`id_f`),
  KEY `fk_c` (`id_c`)
) ENGINE=MyISAM AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `film`
--

INSERT INTO `film` (`id_f`, `nom_f`, `duree_f`, `description_f`, `lien_f`, `image_f`, `catégorie`, `id_c`) VALUES
(1, 'Inception', 148, 'Au lieu de subtiliser un rêve, un voleur expérimenté et son équipe doivent faire l\'inverse : implanter une idée dans l\'esprit d\'un individu. S\'ils y parviennent, il pourrait s\'agir du crime parfait ...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/UGxyBahBPlI?si=xCwSjRuZaOpJ_lXB\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg', 'Science-Fiction', 1),
(2, 'Seigneur des anneaux', 200, 'Les armées de Sauron ont attaqué Minas Tirith, la capitale de Gondor. Jamais ce royaume autrefois puissant n\'a eu autant besoin de son roi. Mais Aragorn trouvera-t-il en lui la volonté d\'accomplir sa destinée ?\r\n\r\nTandis que Gandalf s\'efforce de soutenir les forces brisées de Gondor, Théoden exhorte les guerriers de Rohan à se joindre au combat. Mais malgré leur courage et leur loyauté, les forces des Hommes ne sont pas de taille à lutter contre les innombrables légions d\'ennemis qui s\'abattent sur le royaume...\r\n\r\nChaque victoire se paye d\'immenses sacrifices. Malgré ses pertes, la Communauté se jette dans la bataille pour la vie, ses membres faisant tout pour détourner l\'attention de Sauron afin de donner à Frodon une chance d\'accomplir sa quête.\r\n\r\nVoyageant à travers les terres ennemies, ce dernier doit se reposer sur Sam et Gollum, tandis que l\'Anneau continue de le tenter...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xLWxiDO2WT0?si=_G3YRatwErsZELdu\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://musicart.xboxlive.com/7/a8250500-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'Science-Fiction', 1),
(3, 'Blade Runner', 117, 'En l\'an 2019, un ex-policier devenu détective privé, Rick Deckard, est rappelé en service pour faire la chasse à des robots d\'apparence humaine appelés \"replicants.\" Deckard doit en éliminer quatre qui se cachent à Los Angeles.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RfQEEVcDJ7Q?si=mLQxnM_3OPfYuf_r\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg', 'Science-Fiction', 1),
(4, 'Alien', 117, 'En 2122, le vaisseau commercial Nostromo et son équipage en hibernation, font route vers la Terre avec une importante cargaison de minerai. Un signal, émanant d’une planète inconnue, les tire de leur sommeil artificiel. Intrigué, l’équipage se rend sur place et découvre les restes d\'un gigantesque vaisseau extraterrestre. Lors de l’exploration de l’épave, l\'officier Kane se fait agresser par une forme de vie inconnue.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/zexg_gTV2YE?si=sGa3EenWfwxGmkBo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjhk3hj_o1_VZKKI2W3HlzoPmXZJyiQ0FB-ktqu2L27ZH_rnd6YHjoBSQNj_27TPmsHu0&usqp=CAU', 'Science-Fiction', 1),
(5, '2001 : L\'Odyssée de l\'espace', 160, 'A l\'aube de l\'Humanité, dans le désert africain, une tribu de primates subit les assauts répétés d\'une bande rivale, qui lui dispute un point d\'eau. La découverte d\'un monolithe noir inspire au chef des singes assiégés un geste inédit et décisif.\r\nEn 2001, quatre millions d\'années plus tard, un vaisseau spatial évolue en orbite lunaire au rythme langoureux du \"Beau Danube Bleu\". A son bord, le Dr. Heywood Floyd enquête secrètement sur la découverte d\'un monolithe noir qui émet d\'étranges signaux vers Jupiter.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uS9xNLks-k8?si=IhigZLE9Yy2ZjJvh\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://images.noosfere.org/couv/l/laffont01907-1968.jpg', 'Science-Fiction', 1),
(6, 'Matrix', 136, 'Neo, un des pirates les plus recherchés du cyber-espace, reçoit de mystérieux messages cryptés d\'un certain Morpheus. Celui-ci l\'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu\'est-ce que la Matrice ?', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/XTX3pV9TDSk?si=hW-Cn-3w8eepl4tS\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg', 'Science-Fiction', 1),
(7, 'Interstellar', 179, 'Alors que la vie sur Terre touche à sa fin, un groupe d’explorateurs s’attelle à la mission la plus importante de l’histoire de l’humanité : franchir les limites de notre galaxie pour savoir si l’homme peut vivre sur une autre planète…', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RDG29onvM3Q?si=PL0IhtTtX7CvDsyg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img6.acsta.net/pictures/14/09/24/12/08/158828.jpg', 'Science-Fiction', 1),
(8, 'Piège de cristal', 131, 'John McClane, policier new-yorkais, est venu rejoindre pour les fêtes de Noël sa femme Holly, dont il est séparé depuis plusieurs mois, dans le secret espoir d\'une réconciliation. Celle-ci est cadre dans une multinationale japonaise, la Nakatomi Corporation. Son patron, M. Takagi, donne une soirée en l\'honneur de ses employés, à laquelle assiste McClane. Tandis qu\'il s\'isole pour téléphoner, un commando investit l\'immeuble et coupe toutes les communications avec l\'extérieur.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/rf79c9Da83I?si=Vuc0hDWDVrPJGBZY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img2.acsta.net/pictures/14/08/14/12/00/419467.jpg', 'Action', 2),
(9, 'Mad Max - Fury Road', 120, 'Max est capturé et fait prisonnier dans la Citadelle dirigée par Immortan Joe. C’est alors qu\'il se retrouve embarqué dans une course poursuite explosive.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/NBII7UTxwEY?si=uAzdifQE9T5aY9Qo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg', 'Action', 2),
(10, 'Terminator 2 - Le Jugement dernier', 137, 'En 2029, après son échec pour éliminer Sarah Connor, Skynet programme un nouveau Terminator, le T-1000, pour retourner dans le passé et éliminer son fils John Connor, futur leader de la résistance humaine.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/iXy0aDCGAtU?si=J0r52VTLl7mCxo12\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg', 'Action', 2),
(11, 'Une journée en enfer', 131, 'À New York, une bombe explose dans un grand magasin. Peu de temps après, un homme du nom de Simon contacte la police et revendique l\'attentat. Il exige que le lieutenant John McClane, alors suspendu de ses fonctions, se livre à un petit jeu mortel à travers toute la ville...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xls8o8psgi8?si=cdcDAfHCswpjtcKH\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://lh4.googleusercontent.com/proxy/VS-ukWRxiTgwzpcaqDqDRQe0gkOjK_r4O5XqRC0k_aXrWape17UQPHPs7pyRRe6Meiespy_ogb_0v8hdbvHGr49II26ssirRnf4c4WP7j5RSxuHmlLlycVriaFXix6JsFHjnGddA0Ud-TmLrS-z8WlZ7BLJ2Olk', 'Action', 2),
(12, 'Kill Bill - Volume 1', 111, 'Au cours d\'une cérémonie de mariage en plein désert, un commando fait irruption dans la chapelle et tire sur les convives. Laissée pour morte, la Mariée enceinte retrouve ses esprits après un coma de quatre ans. Celle qui a auparavant exercé les fonctions de tueuse à gages au sein du Détachement International des Vipères Assassines n\'a alors plus qu\'une seule idée en tête : venger la mort de ses proches en éliminant tous les membres de l\'organisation criminelle, dont leur chef Bill qu\'elle se réserve pour la fin.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/WtRpzlIaM6A?si=7K0unQT0zmXaRdrW\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img2.acsta.net/medias/nmedia/18/35/13/44/18364816.jpg', 'Action', 2),
(13, 'The Dark Knight - Le Chevalier noir', 152, 'Avec l\'appui du lieutenant de police Jim Gordon et du procureur de Gotham, Harvey Dent, Batman vise à éradiquer le crime organisé qui pullule dans la ville. Leur association est très efficace, mais elle sera bientôt bouleversée par le chaos déclenché par un criminel psychopathe que les citoyens de Gotham connaissent sous le nom de Joker.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/XGqgxGBn7Qw?si=g6LYJYCibzvwhKbc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://medias.boutique.lab.arte.tv/prod/69209_vod_thumb_315491.jpg', 'Action', 2),
(14, 'Predator', 107, 'Le commando de forces spéciales mené par le major Dutch Schaeffer est engagé par la CIA pour sauver les survivants d’un crash d’hélicoptère au cœur d’une jungle d’Amérique Centrale. Sur place, Dutch et son équipe ne tardent pas à découvrir qu’ils sont pris en chasse par une mystérieuse créature invisible qui commence à les éliminer un par un. La traque commence.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/3MtPyy5bqXg?si=p_s_0zJIB1HEZz9B\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Predator_Movie.jpg/220px-Predator_Movie.jpg', 'Action', 2),
(15, 'Les Aventuriers de l\'arche perdue', 115, 'En 1936, le professeur d\'archéologie Indiana Jones, reçoit la mission de récupérer le médaillon de Râ, que détient son ancienne «fiancée», Marion Ravenwood, maintenant tenancière d\'un bar au fin fond du Népal. Cet objet égyptien permettrait de découvrir le lieu secret où se trouve l\'Arche d\'Alliance. Mais les nazis cherchent, eux aussi, à récupérer cet objet aux pouvoirs extraordinaires. Marion et Indiana s\'engagent alors dans une incroyable quête à travers le monde pour retrouver la mystérieuse Arche d\'Alliance.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/gBdoKaW0o9M?si=cYgwhxJrHFSTsKVb\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img4.acsta.net/medias/nmedia/00/02/49/18/affiche.jpg', 'Aventure', 3),
(16, 'Indiana Jones et la Dernière Croisade', 127, 'En 1938, Indiana Jones se lance sur les traces du Saint Graal, avec l\'aide de son père, le professeur Henry Jones. Mais la coupe sainte est convoitée par les nazis ainsi que Donovan, un milliardaire fasciné par les vertus d\'immortalité qu\'on prête au calice sacré. Les Jones vont devoir affronter mille dangers pour parvenir à récupérer le Graal avant que l\'armée du Reich ne s\'en empare.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/1dFICtrt83s?si=VNrNDUoenWhmKD8e\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://musicart.xboxlive.com/7/56b15100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'Aventure', 3),
(17, 'Indiana Jones et le Temple maudit', 108, 'À Shanghai, en 1935, l\'aventurier et archéologue Indiana Jones négocie l\'acquisition d\'une pierre magique avec le caïd Lao Che. Mais le ton monte entre les deux hommes. Aidé par un enfant chinois surnommé Demi-Lune, Indiana Jones prend la fuite en compagnie la chanteuse américaine Willie Scott. Tous trois sont contraints de quitter la ville à bord d\'un avion de fortune, puis forcés d\'atterrir en Inde.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/8pFxhoKJhLU?si=RpTufY13D-kaN2RC\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img3.acsta.net/medias/nmedia/18/65/88/36/18931015.jpg', 'Aventure', 3),
(18, 'Jurassic Park', 127, 'Sur une île au large du Costa Rica, des scientifiques, financés par le milliardaire John Hammond, ont réussi à cloner des animaux préhistoriques. Leur découverte a permis de créer un parc d\'attractions peuplé de dinosaures. Avant l\'ouverture au public, Hammond demande à Alan et Ellie, deux paléontologues de renom, de cautionner son projet. Mais lors de la première inspection, le système de sécurité se détraque.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/b_R9XDSfhfE?si=lG8JSH51IzDNmuMF\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img4.acsta.net/pictures/20/07/21/16/53/1319265.jpg', 'Aventure', 3),
(19, 'Pirates des Caraïbes - La Malédiction du Black Pearl', 143, 'Au XVIIe siècle, le flibustier Jack Sparrow regagne Port-Royal sur un bateau de fortune. Mais le pirate Barbossa, capitaine du Black Pearl, attaque la ville et enlève Elizabeth, la fille du gouverneur. Will, un forgeron amoureux de la jeune femme, persuade Jack de l\'aider à la délivrer. Will ignore qu\'une malédiction frappe Barbossa et ses pirates qui se transforment en morts-vivants chaque nuit de pleine lune.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/1-UJlChds5I?si=HfTGCGeleMGrC9H5\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img4.acsta.net/medias/nmedia/18/35/07/46/affiche2.jpg', 'Aventure', 3),
(20, 'Retour vers le futur', 116, 'En 1985, Marty, un adolescent comme les autres, mène une existence qu\'il juge morne et ennuyeuse. Heureusement, il est épris de la jolie Jennifer et entretient une profonde amitié avec Doc, un savant fou qui prétend avoir inventé une machine à explorer le temps. Un jour, Doc invite Marty à l\'essayer. Mais ils sont surpris par des terroristes. Doc est abattu tandis que Marty met l\'engin en marche et se retrouve en 1955.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/saCXL-Xfbwk?si=qrreD25J-n4dHD9N\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img2.acsta.net/pictures/22/07/22/15/00/2862661.jpg', 'Aventure', 3),
(21, 'La Guerre des étoiles', 121, 'Dans une galaxie lointaine, l\'univers est dominé par l\'Empire galactique avec à sa tête le sombre et impitoyable Dark Vador. Mais la révolte gronde, l\'Alliance rebelle menée par la princesse Leia, s\'empare des plans de l\'Etoile Noire, la base secrète de l\'Empire. Avant d\'être capturée par les forces impériales, la jeune princesse dissimule les plans de l\'Etoile Noire à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, les deux robots s\'échouent sur la planète Tatooine et terminent leur quête chez le jeune Luke Skywalker. Rêvant de devenir pilote, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/pZSk06DXtnY?si=5L9R1AHGM_SWwWi3\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://www.cinemaffiche.fr/4017-tm_large_default/star-wars-la-guerre-des-etoiles-episode-4-star-wars.jpg', 'Aventure', 3),
(22, 'Shining', 119, 'Écrivain, Jack Torrance est engagé comme gardien, pendant tout l’hiver, d’un grand hôtel isolé du Colorado, l’Overlook, où il espère surmonter enfin sa panne d’inspiration. Il s’y installe avec sa femme Wendy et son fils Danny, doté d’un don de médium. Tandis que Jack n’avance pas dans son livre et que son fils est de plus en plus hanté par des visions terrifiantes, il découvre les terribles secrets de l’hôtel et bascule peu à peu dans une forme de folie meurtrière où il s’en prend à sa propre famille…', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7gQNjXJPlzc?si=Bs111bVsP3O4atuO\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://media.posterlounge.com/img/products/710000/705435/705435_poster.jpg', 'Horreur', 4),
(23, 'L\'Exorciste', 122, 'L\'actrice Chris McNeil est inquiète au sujet de sa fille Regan. Après avoir entendu des bruits étranges venant de sa chambre, la petite a changé, proférant de constantes insanités. Une force para-normale l\'habite, qui coûte la vie au metteur en scène de Chris. Désespérée, cette dernière fait appel à deux exorcistes...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/kuowPVqvnRk?si=KED_glv_Dngr3Uuy\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img5.acsta.net/medias/nmedia/18/65/19/82/18835952.jpg', 'Horreur', 4),
(24, 'The Thing', 84, 'Au cœur de l’Antarctique, une équipe de chercheurs découvre un corps enfoui sous la neige depuis plus de 100 000 ans. Décongelée, la créature retourne à la vie en prenant la forme de celui qu’elle veut ; dès lors, le soupçon s’installe entre les hommes de l’équipe. Où se cache la créature ? Qui habite-t-elle ? Un véritable combat s’engage.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/PXRCJj33ONg?si=4ytwTnn3f_IhYhfe\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://s3.amazonaws.com/nightjarprod/content/uploads/sites/238/2024/01/09165723/tzGY49kseSE9QAKk47uuDGwnSCu.jpg', 'Horreur', 4),
(25, 'Psychose', 107, 'Phoenix, Arizona. Marion Crane, une employée modèle, vole 40 000 dollars à son patron pour permettre à son amant, Sam Loomis, d\'éponger ses dettes. Elle s\'enfuit en voiture dans l\'intention de le rejoindre chez lui en Californie. Sur la route, une forte pluie l\'oblige à s\'arrêter. Elle descend dans un motel isolé, tenu par le jeune et sympathique gérant, Norman Bates.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/78R7w5zhOc8?si=tifjUBWlco-HGs-W\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img2.acsta.net/pictures/22/04/06/14/34/3532106.jpg', 'Horreur', 4),
(26, 'Massacre à la tronçonneuse', 83, 'Dans les années 70, jeunes et insouciants, cinq amis sillonnent le Texas en minibus. Ils croisent en chemin la route d\'un auto-stoppeur et décident de le prendre à bord. Mais lorsque les jeunes gens s\'aperçoivent que l\'individu a un comportement inquiétant et menaçant, ils finissent par s\'en débarrasser. Bientôt à court d\'essence, le groupe décide d\'aller visiter une vieille maison abandonnée.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/OAjVRcgIne0?si=jBvDF3fXq4SFww3h\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fusion.molotov.tv/arts/i/446x588/Ch8SHQoUGAAV08L584Fd6RwXunC1Lpmx_5ASA2pwZxgB/jpg', 'Horreur', 4),
(27, 'Scream', 111, 'Terrorisée par un serial killer s\'inspirant des plus grands films d\'horreur pour exécuter ses crimes, une petite ville devient le terrain d\'une vaste enquête où tout le monde est suspect...', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/d7yWagIcCLE?si=A8o19KKH90IzXYjd\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://m.media-amazon.com/images/M/MV5BYjExYTcwYmYtMWY2Zi00MGJlLTk3YjUtZTU1Zjg4MDc0Y2FjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg', 'Horreur', 4),
(28, 'Evil Dead', 85, 'Cinq jeunes amis, partent en vacances et s\'installent dans une cabane perdue en pleine forêt. En descendant dans une cave lugubre, les deux garçons de la bande découvrent un vieux magnétophone qui, une fois remis en marche, émet une incantation et libère des forces maléfiques. Ce qui semblait être un week-end paisible, se transforme très vite en un véritable cauchemar.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/UgtNwqrit5A?si=Th-LhmaK1BWcIaAD\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://www.ecranlarge.com/uploads/image/001/123/mi5prkqox5nmzqv4n7n6avawxqk-305.jpg', 'Horreur', 4),
(29, 'Il était une fois dans l\'Ouest', 175, 'Alors qu\'il prépare une fête pour sa femme, Bet McBain est tué avec ses trois enfants. Jill McBain hérite alors des terres de son mari, terres que convoite Morton, le commanditaire du crime (celles-ci ont de la valeur maintenant que le chemin de fer doit y passer). Mais les soupçons se portent sur un aventurier, Cheyenne...\r\n\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/o6VsfT3AQyw?si=pol8jbuaag13aKrr\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://www.on-mag.fr/images/stories/2011/08/ouverture-il-etait-une-foi-dans-l-ouest.jpg', 'Western', 5),
(30, 'Le Bon, la brute et le truand', 180, 'Pendant la Guerre de Sécession, trois hommes, préférant s\'intéresser à leur profit personnel, se lancent à la recherche d\'un coffre contenant 200 000 dollars en pièces d\'or volés à l\'armée sudiste. Tuco sait que le trésor se trouve dans un cimetière, tandis que Joe connaît le nom inscrit sur la pierre tombale qui sert de cache. Chacun a besoin de l\'autre. Mais un troisième homme entre dans la course : Setenza, une brute qui n\'hésite pas à massacrer femmes et enfants pour parvenir à ses fins.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/WA1hCZFOPqs?si=ms_8IAGyKL44RM6H\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img2.acsta.net/pictures/14/09/23/10/28/237103.jpg', 'Western', 5),
(31, 'Django Unchained', 164, 'Dans le sud des États-Unis, deux ans avant la guerre de Sécession, le Dr King Schultz, un chasseur de primes allemand, fait l’acquisition de Django, un esclave qui peut l’aider à traquer les frères Brittle, les meurtriers qu’il recherche. Schultz promet à Django de lui rendre sa liberté lorsqu’il aura capturé les Brittle – morts ou vifs.\r\n\r\nAlors que les deux hommes pistent les dangereux criminels, Django n’oublie pas que son seul but est de retrouver Broomhilda, sa femme, dont il fut séparé à cause du commerce des esclaves…\r\n\r\nLorsque Django et Schultz arrivent dans l’immense plantation du puissant Calvin Candie, ils éveillent les soupçons de Stephen, un esclave qui sert Candie et a toute sa confiance. Le moindre de leurs mouvements est désormais épié par une dangereuse organisation de plus en plus proche… Si Django et Schultz veulent espérer s’enfuir avec Broomhilda, ils vont devoir choisir entre l’indépendance et la solidarité, entre le sacrifice et la survie…', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/t23Huo3DsKc?si=LnVnGV4KEpFeJz3Z\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img6.acsta.net/medias/nmedia/18/90/08/59/20366454.jpg', 'Western', 5),
(32, 'Danse avec les loups', 244, 'Le jeune lieutenant John Dunbar est envoyé à un poste de reconnaissance dans les immenses plaines du Dakota pendant la guerre de Sécession. Il rencontre au cours de l\'une de ses missions de reconnaissance le peuple sioux.\r\n\r\nLe lieutenant se lie d\'amitié avec la population indienne. Il arrive même à intégrer la tribu, au point d\'être surnommé \"Danse avec les loups\", et de s\'éprendre d\'une des leurs, une blanche baptisée \"Dressée avec le poing\".', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dbYwm6IBq54?si=GMm3J9ItoTDHRFqr\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img5.acsta.net/medias/nmedia/18/83/23/81/19672460.jpg', 'Western', 5),
(33, 'Et pour quelques dollars de plus', 190, '\" L\'indien \", bandit cruel et fou, s\'est évadé de prison. Il se prépare à attaquer la banque d\'El Paso, la mieux gardée de tout l\'Ouest, avec une quinzaine d\'autres malfaiteurs. Le \" Manchot \" et le Colonel Douglas Mortimer, deux chasseurs de primes concurrents, décident, après une confrontation tendue, de faire finalement équipe pour arrêter les bandits. Mais leurs motivations ne sont pas forcément les mêmes...\r\n\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/_0fFfnzIyCg?si=0vcKweuThZQa6Gu_\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img4.acsta.net/medias/nmedia/18/64/43/31/19182254.jpg', 'Western', 5),
(34, 'Impitoyable', 131, 'Kansas 1880. William Munny, redoutable hors-la-loi reconverti dans l\'élevage va, à la demande d\'un jeune tueur, reprendre du service pour venger une prostituée défigurée par un cow-boy sadique.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xzFJN8yJ4KQ?si=37Oxgg2LTNCA6SsI\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img5.acsta.net/pictures/17/06/08/15/03/455505.jpg', 'Western', 5),
(35, 'Little Big Man', 139, 'Âgé de 121 ans, Jack Crabb, seul survivant du massacre de Little Big Horn, raconte son histoire à un journaliste. Adopté par une famille de Cheyennes, ce visage pâle est surnommé Little Big Man à cause de son immense courage. Un jour, toute sa tribu est massacrée par les Blancs et Jack est alors recueilli par un pasteur et sa femme. Mais le jeune homme est partagé entre ses origines indiennes et son nouveau peuple..', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/QGw--2q6L3g?si=daAzk10GzTX6GyAj\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'https://fr.web.img6.acsta.net/pictures/16/06/30/14/29/221991.jpg', 'Western', 5);

-- --------------------------------------------------------

--
-- Structure de la table `regarder`
--

DROP TABLE IF EXISTS `regarder`;
CREATE TABLE IF NOT EXISTS `regarder` (
  `id_f` int NOT NULL,
  `id_u` int NOT NULL,
  `regarder` int NOT NULL,
  `note` float NOT NULL,
  `commentaire` text NOT NULL,
  PRIMARY KEY (`id_f`,`id_u`),
  KEY `id_u` (`id_u`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id_u` int NOT NULL AUTO_INCREMENT,
  `login` varchar(35) NOT NULL,
  `mdp` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `lvl` int NOT NULL,
  `date_deb_abo` datetime NOT NULL,
  `date_fin_abo` datetime NOT NULL,
  PRIMARY KEY (`id_u`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
